import Head from 'next/head'
import CreateDocumentSection from '../components/CreateDocumentSection'
import DocumentList from '../components/DocumentList'
import Header from '../components/Header'
import { useSession, getSession } from "next-auth/client"
import Login from '../components/Login'


export default function Home() {

  // const { session, status } = useSession()
  const [session, loading] = useSession();

  // console.log("SESSION 🧐 : ", session);
  // console.log("STATUS 🔥 : ", status);

  // if (status != "authenticated") {
  //   return <Login />
  // }

  if (!session) return <Login />

  return (

    <div className="">
      <Head>
        <title>NextDocs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <CreateDocumentSection />
      <DocumentList />

    </div >
  )
}


export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    }, // will be passed to the page component as props
  }
}